### ISSUE TITLE
クエリの外部化(ファイルに出す、とか)

### ISSUE THREAD

**Issue by jnuank** [t2-kob/ModelingKai-Reservation#24]
- クエリを定数にする (可変部は@)
  - クエリをメソッドにする
  - クエリを外部ファイルにする

**Comment by nsiena** [comment]
クエリの外部ファイル化は不要派。

クエリを必要性を感じない理由:
* クエリのバリエーションが出てきて、実行コンテキストに応じて使い分ける場面が想像できない。他言語対応とは違って。
* ソースコードを編集しないメンバがそれを書き換えたり参照したりする状況も存在できない。翻訳とか、メッセージ定義とかと違って
* SQLクエリ文と、クエリパラメータは、強い相関があるので、泣き別れになるのはいけてない。混乱の原因になったり、探し回ったり、あっち行ったりこっち行ったりで煩雑になったりする原因になりそう。

**Comment by jnuank** [comment]
いまはやめておく。という感じで、Doneする
